name: extended_image
description: Official extension image, support placeholder(loading)/ failed state, cache network, zoom/pan, photo view, slide out page, editor(crop,rotate,flip), painting etc.
version: 8.1.1
repository: https://github.com/fluttercandies/extended_image
issue_tracker: https://github.com/fluttercandies/extended_image/issues

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.13.0'

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

dependencies:
#  extended_image_library: ^3.6.0
  extended_image_library:
    git:
      url: https://github.com/behrangnm/extended_image_library.git
  flutter:
    sdk: flutter
  meta: ^1.7.0
dependency_overrides:
