name: extended_image
description: Official extension image, support placeholder(loading)/ failed state, cache network, zoom/pan, photo view, slide out page, editor(crop,rotate,flip), painting etc.
version: 9.0.7
repository: https://github.com/fluttercandies/extended_image
issue_tracker: https://github.com/fluttercandies/extended_image/issues

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.16.0'

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

dependencies:
  extended_image_library:
    git:
      url: https://github.com/behrangnm/extended_image_library.git
  flutter:
    sdk: flutter
  meta: ^1.7.0
  vector_math: ^2.1.4
dependency_overrides:
  # extended_image_library:
  #   path: ../extended_image_library

